apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment 
  namespace: default
spec:
  replicas: 3  # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: busybox  # Replace with your container image
        ports:
        - containerPort: 80  # Port your application listens on
